# -*- coding: utf-8 -*-
"""alldata_segemntation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kc_7FXaL7fco-Ur9Nyw8BRCOywOqZ3m6
"""

# Mount Google Drive to access files
from google.colab import drive
drive.mount('/content/drive')
print("Google Drive has been mounted successfully.")

import os

# Define the directory where the XML files are located
# List all files and directories within the specified path
files_in_mydrive = os.listdir('/content/drive/MyDrive/Biorad/xml_files')

# Print the list of files to verify contents
for item in files_in_mydrive:
    print(item)

#1. Load XML and inspect top-level structure
import xml.etree.ElementTree as ET

xml_path = "/content/drive/MyDrive/Biorad/xml_files/591-ws-training.xml"

tree = ET.parse(xml_path)
root = tree.getroot()

print("Root tag:", root.tag)
print("Patient attributes:", root.attrib)

print("\nTop level sections:")
for child in root:
    print(child.tag)

#2. Extract all attribute names used in events
from collections import defaultdict

tag_attributes = defaultdict(set)

for section in root:

    for event in section.findall("event"):

        for attr in event.attrib:
            tag_attributes[section.tag].add(attr)

print("\nAttributes used in each section:\n")

for tag, attrs in tag_attributes.items():
    print(tag, "->", sorted(list(attrs)))

#3. Count number of events in each section
print("\nEvent counts per section:\n")

for section in root:
    events = section.findall("event")
    print(section.tag, ":", len(events))

#4. Detect timestamp fields used
timestamp_fields = set()

for section in root:
    for event in section.findall("event"):
        for attr in event.attrib:
            if "ts" in attr:
                timestamp_fields.add(attr)

print("Timestamp fields found:", timestamp_fields)

#5. Collect all unique attributes globally
all_attributes = set()

for section in root:
    for event in section.findall("event"):
        all_attributes.update(event.attrib.keys())

print("\nAll event attributes found:\n")
print(sorted(all_attributes))

#6. Print a few example events for each section
for section in root:

    print("\nSECTION:", section.tag)

    for i, event in enumerate(section.findall("event")[:3]):
        print(event.attrib)

import xml.etree.ElementTree as ET
import pandas as pd
import numpy as np


STANDARD_COLUMNS = [
    "patient_id","timestamp",
    "glucose_level","finger_stick","basal","temp_basal",
    "bolus_dose","bolus_carb_input","bolus_type",
    "meal_type","meal_carbs",
    "exercise_intensity","exercise_duration","exercise_competitive",
    "sleep_quality","basis_sleep_quality",
    "hypo_event",
    "illness_type","illness_description",
    "basis_heart_rate","basis_gsr","basis_skin_temperature",
    "basis_air_temperature","basis_steps"
]


def clean(v):
    if v is None:
        return np.nan
    v = str(v).strip()
    if v == "":
        return np.nan
    return v


def parse_time(t):
    if t is None or t == "":
        return None
    return pd.to_datetime(t, format="%d-%m-%Y %H:%M:%S")


def expand_interval(start, end):
    """expand interval only if gap >5 minutes"""
    times = [start]
    cur = start

    while True:
        nxt = cur + pd.Timedelta(minutes=5)
        if nxt >= end:
            break
        times.append(nxt)
        cur = nxt

    times.append(end)
    return times


def parse_diabetes_xml(xml_path):

    tree = ET.parse(xml_path)
    root = tree.getroot()

    patient_id = root.attrib.get("id")

    rows = {}

    def get_row(ts):
        if ts not in rows:
            rows[ts] = {c: np.nan for c in STANDARD_COLUMNS}
            rows[ts]["timestamp"] = ts
            rows[ts]["patient_id"] = patient_id
        return rows[ts]


    for section in root:

        tag = section.tag

        for event in section.findall("event"):

            a = event.attrib

            ts = parse_time(a.get("ts") or a.get("ts_begin") or a.get("tbegin"))
            ts_end = parse_time(a.get("ts_end") or a.get("tend"))

            if ts is None:
                continue

            if ts_end is not None and ts_end < ts:
                ts, ts_end = ts_end, ts

            # ---------- GLUCOSE ----------
            if tag == "glucose_level":

                val = clean(a.get("value"))
                if val is None:
                    continue

                row = get_row(ts)
                row["glucose_level"] = float(val)


            # ---------- FINGER STICK ----------
            elif tag == "finger_stick":

                row = get_row(ts)
                row["finger_stick"] = float(clean(a.get("value")))


            # ---------- BASAL ----------
            elif tag == "basal":

                row = get_row(ts)
                row["basal"] = float(clean(a.get("value")))


            # ---------- TEMP BASAL ----------
            elif tag == "temp_basal":

                if ts_end is None:
                    ts_end = ts

                times = expand_interval(ts, ts_end)

                val = float(clean(a.get("value")))

                for t in times:
                    row = get_row(t)
                    row["temp_basal"] = val   # overwrite allowed


            # ---------- BOLUS ----------
            elif tag == "bolus":

                row = get_row(ts)

                row["bolus_dose"] = float(clean(a.get("dose")))
                row["bolus_carb_input"] = float(clean(a.get("bwz_carb_input")))
                row["bolus_type"] = clean(a.get("type"))


            # ---------- MEAL ----------
            elif tag == "meal":

                row = get_row(ts)

                row["meal_type"] = clean(a.get("type"))
                row["meal_carbs"] = float(clean(a.get("carbs")))


            # ---------- EXERCISE ----------
            elif tag == "exercise":

                intensity = float(clean(a.get("intensity")))
                duration = clean(a.get("duration"))

                if duration is not None:
                    ts_end = ts + pd.Timedelta(minutes=float(duration))
                else:
                    ts_end = ts

                times = expand_interval(ts, ts_end)

                for t in times:
                    row = get_row(t)
                    row["exercise_intensity"] = intensity
                    row["exercise_duration"] = float(duration)
                    row["exercise_competitive"] = clean(a.get("competitive"))


            # ---------- SLEEP ----------
            elif tag == "sleep":

                if ts_end is None:
                    ts_end = ts

                times = expand_interval(ts, ts_end)

                quality = float(clean(a.get("quality")))

                for t in times:
                    row = get_row(t)
                    row["sleep_quality"] = quality


            # ---------- BASIS SLEEP ----------
            elif tag == "basis_sleep":

                if ts_end is None:
                    ts_end = ts

                times = expand_interval(ts, ts_end)

                quality = float(clean(a.get("quality")))

                for t in times:
                    row = get_row(t)
                    row["basis_sleep_quality"] = quality


            # ---------- HYPO ----------
            elif tag == "hypo_event":

                row = get_row(ts)
                row["hypo_event"] = 1


            # ---------- ILLNESS ----------
            elif tag == "illness":

                if ts_end is None:
                    ts_end = ts + pd.Timedelta(days=1)

                times = expand_interval(ts, ts_end)

                for t in times:
                    row = get_row(t)
                    row["illness_type"] = clean(a.get("type"))
                    row["illness_description"] = clean(a.get("description"))


            # ---------- BASIS SENSORS ----------
            elif tag == "basis_heart_rate":

                row = get_row(ts)
                row["basis_heart_rate"] = float(clean(a.get("value")))


            elif tag == "basis_gsr":

                row = get_row(ts)
                row["basis_gsr"] = float(clean(a.get("value")))


            elif tag == "basis_skin_temperature":

                row = get_row(ts)
                row["basis_skin_temperature"] = float(clean(a.get("value")))


            elif tag == "basis_air_temperature":

                row = get_row(ts)
                row["basis_air_temperature"] = float(clean(a.get("value")))


            elif tag == "basis_steps":

                row = get_row(ts)
                row["basis_steps"] = float(clean(a.get("value")))


    df = pd.DataFrame(rows.values())

    df = df.sort_values("timestamp").reset_index(drop=True)

    # basal persistence
    if "basal" in df.columns:
        df["basal"] = df["basal"].ffill()

    return df

import os

folder = "/content/drive/MyDrive/Biorad/xml_files"

patient_dfs = {}

for file in os.listdir(folder):

    if file.endswith(".xml"):

        path = os.path.join(folder, file)

        df = parse_diabetes_xml(path)

        pid = df["patient_id"].iloc[0]

        if pid not in patient_dfs:
            patient_dfs[pid] = []

        patient_dfs[pid].append(df)


# combine training + testing per patient
for pid in patient_dfs:
    patient_dfs[pid] = pd.concat(patient_dfs[pid]).sort_values("timestamp").reset_index(drop=True)


print("Patients loaded:", patient_dfs.keys())

import pandas as pd

excel_path = "/content/drive/MyDrive/Biorad/csv_xlsv_files/patient_alldatapoints.xlsx"
pkl_path   = "/content/drive/MyDrive/Biorad/pkl_files/patient_alldatapoints.pkl"

# -------- Excel with 6 sheets --------
with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:

    for pid, pdf in patient_dfs.items():
        pdf.to_excel(writer, sheet_name=str(pid), index=False)

print("Excel exported:", excel_path)


# -------- PKL file --------
pd.to_pickle(patient_dfs, pkl_path)

print("PKL exported:", pkl_path)

import pandas as pd

excel_path = "/content/drive/MyDrive/Biorad/csv_xlsv_files/all_patient_alldatapoints.xlsx"
pkl_path   = "/content/drive/MyDrive/Biorad/pkl_files/all_patient_alldatapoints.pkl"

# merge all patient dataframes
all_patients_df = pd.concat(patient_dfs.values(), ignore_index=True)

# sort properly
all_patients_df = all_patients_df.sort_values(
    ["patient_id","timestamp"]
).reset_index(drop=True)

# export excel
all_patients_df.to_excel(excel_path, index=False)

# export pkl
all_patients_df.to_pickle(pkl_path)

print("Export complete")
print("Rows:", len(all_patients_df))
print("Columns:", list(all_patients_df.columns))

# sort first
all_patients_df = all_patients_df.sort_values(
    ["patient_id","timestamp"]
).reset_index(drop=True)

# ensure timestamp type
all_patients_df["timestamp"] = pd.to_datetime(all_patients_df["timestamp"])

segments = []

for pid, pdf in all_patients_df.groupby("patient_id"):

    pdf = pdf.sort_values("timestamp").copy()

    # compute gap in minutes
    gap = pdf["timestamp"].diff().dt.total_seconds().div(60)

    # new segment if gap > 10
    seg = (gap > 10).cumsum() + 1

    pdf["segment_id"] = [f"{pid}_S{s}" for s in seg]

    segments.append(pdf)

# combine back
all_patients_df = pd.concat(segments).reset_index(drop=True)

print(all_patients_df[["patient_id","timestamp","segment_id"]].head())
print("Total segments:", all_patients_df["segment_id"].nunique())

excel_path = "/content/drive/MyDrive/Biorad/csv_xlsv_files/all_paitent_alldatapoints_segmented.xlsx"
pkl_path   = "/content/drive/MyDrive/Biorad/pkl_files/all_paitent_alldatapoints_segmented.pkl"

# export excel
all_patients_df.to_excel(excel_path, index=False)

# export pkl
all_patients_df.to_pickle(pkl_path)

print("Export complete")
print("Excel:", excel_path)
print("PKL:", pkl_path)
print("Rows:", len(all_patients_df))
print("Segments:", all_patients_df["segment_id"].nunique())

import pandas as pd

summary_rows = []

for seg, sdf in all_patients_df.groupby("segment_id"):

    start = sdf["timestamp"].min()
    end   = sdf["timestamp"].max()

    duration = end - start
    duration_hours = duration.total_seconds() / 3600

    status = "KEEP" if duration_hours >= 8 else "DISCARD"

    summary_rows.append({
        "segment_id": seg,
        "start_timestamp": start,
        "end_timestamp": end,
        "duration_hours": round(duration_hours,2),
        "status": status
    })

segment_summary_df = pd.DataFrame(summary_rows).sort_values("segment_id").reset_index(drop=True)

print(segment_summary_df.head())
print("Total segments:", len(segment_summary_df))
print(segment_summary_df["status"].value_counts())

# total datapoints
total_points = len(all_patients_df)

# segments to keep
keep_segments = segment_summary_df[segment_summary_df["status"] == "KEEP"]["segment_id"]

# segments to discard
discard_segments = segment_summary_df[segment_summary_df["status"] == "DISCARD"]["segment_id"]

# datapoints per category
keep_points = all_patients_df[all_patients_df["segment_id"].isin(keep_segments)].shape[0]
discard_points = all_patients_df[all_patients_df["segment_id"].isin(discard_segments)].shape[0]

print("Total datapoints:", total_points)
print("Kept datapoints:", keep_points)
print("Discarded datapoints:", discard_points)

excel_path = "/content/drive/MyDrive/Biorad/csv_xlsv_files/summary_all_paitent_alldatapoints_segemnted.xlsx"

segment_summary_df.to_excel(excel_path, index=False)

print("Export complete")
print("Excel:", excel_path)
print("Rows:", len(segment_summary_df))

# get segments to discard
discard_segments = segment_summary_df[
    segment_summary_df["status"] == "DISCARD"
]["segment_id"]

# remove them from main dataset
all_patients_df = all_patients_df[
    ~all_patients_df["segment_id"].isin(discard_segments)
].reset_index(drop=True)

print("Remaining datapoints:", len(all_patients_df))
print("Remaining segments:", all_patients_df["segment_id"].nunique())

for pid, pdf in all_patients_df.groupby("patient_id"):

    print("\nPatient:", pid)
    print("Total timestamps:", len(pdf))

    seg_counts = pdf.groupby("segment_id").size()

    for seg, count in seg_counts.items():
        print(seg, ":", count)

import pandas as pd

MIN_POINTS = 96  # 8 hours at 5-min sampling

df = all_patients_df.sort_values(["patient_id","timestamp"]).copy()
df["split"] = None

def split_segment(pdf, split_point):
    # split pdf at split_point index (position in pdf)
    left = pdf.iloc[:split_point].copy()
    right = pdf.iloc[split_point:].copy()
    return left, right

new_rows = []

for pid, pdf in df.groupby("patient_id"):
    pdf = pdf.sort_values("timestamp").copy()
    total = len(pdf)

    train_target = int(total * 0.7)
    test_target  = int(total * 0.9)

    cum = 0

    for seg_id, seg_df in pdf.groupby("segment_id", sort=False):
        seg_len = len(seg_df)

        # determine current phase
        if cum < train_target:
            phase = "TRAIN"
            boundary = train_target
        elif cum < test_target:
            phase = "TEST"
            boundary = test_target
        else:
            phase = "VALIDATE"
            boundary = None

        if boundary is None:
            seg_df["split"] = "VALIDATE"
            new_rows.append(seg_df)
            cum += seg_len
            continue

        if cum + seg_len <= boundary:
            seg_df["split"] = phase
            new_rows.append(seg_df)
            cum += seg_len
        else:
            # need to split this segment
            need = boundary - cum

            if need >= MIN_POINTS and (seg_len - need) >= MIN_POINTS:
                left, right = split_segment(seg_df, need)

                left["split"] = phase
                left["segment_id"] = seg_id + "_A"

                if phase == "TRAIN":
                    next_phase = "TEST"
                elif phase == "TEST":
                    next_phase = "VALIDATE"
                else:
                    next_phase = "VALIDATE"

                right["split"] = next_phase
                right["segment_id"] = seg_id + "_B"

                new_rows.append(left)
                new_rows.append(right)

                cum += seg_len
            else:
                seg_df["split"] = phase
                new_rows.append(seg_df)
                cum += seg_len

df_split = pd.concat(new_rows).sort_values(["patient_id","timestamp"]).reset_index(drop=True)

print(df_split[["patient_id","segment_id","split"]].head())
print(df_split["split"].value_counts())

for pid, pdf in df_split.groupby("patient_id"):

    print("\nPatient:", pid)
    print("Total timestamps:", len(pdf))

    seg_counts = pdf.groupby(["segment_id","split"]).size()

    for (seg, sp), count in seg_counts.items():
        print(seg, "|", sp, ":", count)

# sort properly
df_split = df_split.sort_values(["patient_id","timestamp"]).reset_index(drop=True)

new_dfs = []

for pid, pdf in df_split.groupby("patient_id"):

    pdf = pdf.sort_values("timestamp").copy()

    # detect segment change
    seg_change = pdf["segment_id"].ne(pdf["segment_id"].shift()).cumsum()

    # create new sequential segment ids
    pdf["segment_id"] = seg_change.apply(lambda x: f"{pid}_S{x}")

    new_dfs.append(pdf)

df_split = pd.concat(new_dfs).reset_index(drop=True)

print(df_split[["patient_id","timestamp","segment_id","split"]].head())
print("Total segments:", df_split["segment_id"].nunique())

# --- Adjust segments for patient 588 ---

pid = "588"

pdf = df_split[df_split["patient_id"] == pid].sort_values("timestamp").copy()

# original segments
s1 = pdf[pdf["segment_id"] == "588_S1"]
s2 = pdf[pdf["segment_id"] == "588_S2"]
s3 = pdf[pdf["segment_id"] == "588_S3"]
s4 = pdf[pdf["segment_id"] == "588_S4"]

# split S3 and S4
s3a = s3.iloc[:12000].copy()
s3b = s3.iloc[12000:].copy()

s4a = s4.iloc[:7000].copy()
s4b = s4.iloc[7000:].copy()

# assign new segment IDs
s1["segment_id"] = "588_S1"
s2["segment_id"] = "588_S2"
s3a["segment_id"] = "588_S3"
s3b["segment_id"] = "588_S4"
s4a["segment_id"] = "588_S5"
s4b["segment_id"] = "588_S6"

# assign splits
s1["split"] = "TRAIN"
s2["split"] = "TRAIN"
s3a["split"] = "TRAIN"

s3b["split"] = "TEST"
s4a["split"] = "TEST"

s4b["split"] = "VALIDATE"

# combine back
pdf_new = pd.concat([s1, s2, s3a, s3b, s4a, s4b])

# replace in main dataframe
df_split = pd.concat([
    df_split[df_split["patient_id"] != pid],
    pdf_new
]).sort_values(["patient_id","timestamp"]).reset_index(drop=True)

print(df_split[df_split["patient_id"]=="588"].groupby(["segment_id","split"]).size())

import pandas as pd

rows = []

for pid, pdf in df_split.groupby("patient_id"):

    patient_total_points = len(pdf)
    patient_segments = pdf["segment_id"].nunique()

    for split, spdf in pdf.groupby("split"):

        seg_counts = spdf.groupby("segment_id").size()

        # individual segment rows
        for seg, count in seg_counts.items():
            rows.append({
                "patient_id": pid,
                "split": split,
                "segment_id": seg,
                "points": count
            })

        # split total row
        rows.append({
            "patient_id": pid,
            "split": f"{split}_TOTAL",
            "segment_id": ",".join(seg_counts.index),
            "points": seg_counts.sum()
        })

    # patient total row
    rows.append({
        "patient_id": f"{pid}_TOTAL",
        "split": "TOTAL",
        "segment_id": patient_segments,
        "points": patient_total_points
    })

summary_excel_df = pd.DataFrame(rows)

excel_path = "/content/drive/MyDrive/Biorad/csv_xlsv_files/patient_segment_split_summary.xlsx"

summary_excel_df.to_excel(excel_path, index=False)

print("Export complete")
print("Excel:", excel_path)

df_split = df_split.dropna(axis=1, how="all")

excel_path = "/content/drive/MyDrive/Biorad/csv_xlsv_files/all_combined.xlsx"
pkl_path   = "/content/drive/MyDrive/Biorad/pkl_files/all_combined.pkl"

df_split.to_excel(excel_path, index=False)
df_split.to_pickle(pkl_path)

print("Export complete")
print("Rows:", len(df_split))
print("Segments:", df_split["segment_id"].nunique())

import pandas as pd

print("===== DATASET SUMMARY =====")

# total rows
print("Total rows:", len(df_split))

# total patients
print("Total patients:", df_split["patient_id"].nunique())

# total segments
print("Total segments:", df_split["segment_id"].nunique())

print("\n===== SPLIT DISTRIBUTION =====")
print(df_split["split"].value_counts())

print("\n===== SPLIT PERCENTAGES =====")
split_counts = df_split["split"].value_counts()
print((split_counts / len(df_split) * 100).round(2))

print("\n===== SEGMENTS PER SPLIT =====")
print(df_split.groupby("split")["segment_id"].nunique())

print("\n===== DATA POINTS PER PATIENT =====")
print(df_split.groupby("patient_id").size())

print("\n===== SEGMENTS PER PATIENT =====")
print(df_split.groupby("patient_id")["segment_id"].nunique())

print("\n===== NULL VALUES PER COLUMN =====")
print(df_split.isnull().sum())

print("\n===== NON-NULL VALUES PER COLUMN =====")
print(df_split.notnull().sum())

print("\n===== COLUMN DATA TYPES =====")
print(df_split.dtypes)

segment_summary = (
    df_split
    .groupby(["patient_id","segment_id","split"])
    .size()
    .reset_index(name="points")
    .sort_values(["patient_id","segment_id"])
)

print(segment_summary)

cgm = df_split[df_split["glucose_level"].notna()]

diff = cgm.groupby("patient_id")["timestamp"].diff().dt.total_seconds()/60

print(diff.value_counts())

import pandas as pd
import plotly.graph_objects as go

patient_id = "591"

pdf = df[df["patient_id"] == patient_id].copy()
pdf["timestamp"] = pd.to_datetime(pdf["timestamp"])

continuous_attrs = [
    "basis_heart_rate",
    "basis_steps",
    "basis_gsr",
    "basis_skin_temperature",
    "basis_air_temperature",
    "basis_sleep_quality"
]

event_attrs = [
    "meal_type",
    "exercise_intensity",
    "hypo_event",
    "finger_stick",
    "bolus_dose",
    "basal",
    "temp_basal"
]

# ensure numeric columns
pdf["glucose_level"] = pd.to_numeric(pdf["glucose_level"], errors="coerce")
for attr in continuous_attrs:
    pdf[attr] = pd.to_numeric(pdf[attr], errors="coerce")

fig = go.Figure()

# Glucose trace
fig.add_trace(go.Scatter(
    x=pdf["timestamp"],
    y=pdf["glucose_level"],
    mode="lines+markers",
    connectgaps=True,
    line=dict(width=2),
    marker=dict(size=4),
    name="Glucose",
    yaxis="y1"
))

# Continuous attributes on secondary axis
for attr in continuous_attrs:
    fig.add_trace(go.Scatter(
        x=pdf["timestamp"],
        y=pdf[attr],
        mode="lines+markers",
        connectgaps=True,
        line=dict(width=2),
        marker=dict(size=4),
        name=attr,
        visible=False,
        yaxis="y2"
    ))

buttons = []

# NONE option
buttons.append(dict(
    label="None",
    method="update",
    args=[{"visible":[True]+[False]*len(continuous_attrs)}, {"shapes": []}]
))

# Continuous attribute dropdown
for i, attr in enumerate(continuous_attrs):

    vis = [True] + [False]*len(continuous_attrs)
    vis[i+1] = True

    buttons.append(dict(
        label=attr,
        method="update",
        args=[{"visible": vis}, {"shapes": []}]
    ))

# Event dropdown
for event in event_attrs:

    shapes = []
    events = pdf[pdf[event].notna()]

    for _, r in events.iterrows():
        shapes.append(dict(
            type="line",
            x0=r["timestamp"],
            x1=r["timestamp"],
            y0=0,
            y1=r["glucose_level"],
            line=dict(color="red", dash="dot", width=2)
        ))

    buttons.append(dict(
        label=event,
        method="update",
        args=[{"visible":[True]+[False]*len(continuous_attrs)}, {"shapes": shapes}]
    ))

# Date dropdown based on available dataset dates
unique_dates = sorted(pdf["timestamp"].dt.date.unique())

date_buttons = []

for d in unique_dates:
    start = pd.Timestamp(d)
    end = start + pd.Timedelta(days=1)

    date_buttons.append(dict(
        label=str(d),
        method="relayout",
        args=[{"xaxis.range":[start,end]}]
    ))

fig.update_layout(

    title="Glucose vs Selected Attribute",

    xaxis=dict(
        title="Timestamp",
        type="date",

        rangeselector=dict(
            buttons=[
                dict(count=1, label="1h", step="hour", stepmode="backward"),
                dict(count=6, label="6h", step="hour", stepmode="backward"),
                dict(count=12, label="12h", step="hour", stepmode="backward"),
                dict(count=1, label="1d", step="day", stepmode="backward"),
                dict(count=7, label="7d", step="day", stepmode="backward"),
                dict(step="all")
            ]
        ),

        rangeslider=dict(visible=True)
    ),

    yaxis=dict(
        title="Glucose (mg/dL)",
        range=[0,400],
        type="linear"
    ),

    yaxis2=dict(
        title="Attribute Value",
        overlaying="y",
        side="right",
        showgrid=False
    ),

    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            showactive=True,
            x=1.15,
            y=1
        ),
        dict(
            buttons=date_buttons,
            direction="down",
            showactive=True,
            x=0.35,
            y=1.15
        )
    ],

    template="plotly_white",
    height=650
)

fig.show()

